### ISSUE TITLE
xades/sign imza birinci imza türünden xml imzalarken hata?

### ISSUE THREAD

**Issue by mummyildiz** [kenankocer/DigitalSignature#1]
emeğinize sağlık

**Comment by mummyildiz** [comment]
c:\program files\DSClient\Log klasöründeki en son log kaydı

[1.4.7] 2023-08-22 17:46:36,048 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :80 - Xades sign metodu cagirildi.
[1.4.7] 2023-08-22 17:46:36,049 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :86 - /api/xades/sign - Certificate bilgisi cekildi.
[1.4.7] 2023-08-22 17:46:36,050 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :89 - /api/xades/sign - File decode islemi gerceklestirildi.
[1.4.7] 2023-08-22 17:46:36,050 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :97 - /api/xades/sign - Library decode islemi gerceklestirildi.
[1.4.7] 2023-08-22 17:46:36,051 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :100 - /api/xades/sign - SlotId decode ve parse islemi gerceklestirildi.
[1.4.7] 2023-08-22 17:46:36,051 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :105 - /api/xades/sign - CertificateSerialNumber decode ve parse islemi gerceklestirildi.
[1.4.7] 2023-08-22 17:46:36,051 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.Utilities           :182 - Utilities/getSignatureAlg - ECSignatureAlg alınıyor7alındı.
[1.4.7] 2023-08-22 17:46:36,052 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.Utilities           :185 - Utilities/getSignatureAlg - ECSignatureAlg alınamadı. Yerine SignatureAlg.RSA_SHA512 kullanılacak.
[1.4.7] 2023-08-22 17:46:36,052 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :39 - dscore/XadesSign - Metod cagirildi.
[1.4.7] 2023-08-22 17:46:36,052 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :116 - /api/xades/sign - Sign objesi dolduruldu
[1.4.7] 2023-08-22 17:46:36,052 [INFO ] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :117 - Xades imzalama islemi baslatildi.
[1.4.7] 2023-08-22 17:46:36,053 [INFO ] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :61 - Imza islemi baslatildi.
[1.4.7] 2023-08-22 17:46:36,053 [INFO ] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :43 - dscore/BaseSign/ - createSigner Lock başladi.
[1.4.7] 2023-08-22 17:46:36,053 [DEBUG] [http-nio-3638-exec-1] ..restapi.controllers.XadesController     :44 - dscore/BaseSign/CreateSigner - Metod cagirildi.
[1.4.7] 2023-08-22 17:46:36,057 [ERROR] [http-nio-3638-exec-1] ..restapi.controllers.DigitalSignatureExceptionHandler:45 - 
java.lang.IllegalMonitorStateException
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:149)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1302)
	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:439)
	at com.bimser.dscore.sign.BaseSign.createSigner(BaseSign.java:71)
	at com.bimser.dscore.sign.XadesSign.Sign(XadesSign.java:64)
	at com.bimser.ds.restapi.controllers.XadesController.sign(XadesController.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by kenankocer** [comment]
Mustafa Bey Merhaba,

*Yazdığımız kütüphane open source bi çözüm değil. Bizim projeye koduba
ulaşıp çalıştırdınız onu mu soruyorsunuz? Yoksa kamusm ma3api kütüphanesini
kullanarak kendi projenizi geliştirirken xades de hata alıyorsunuz onu mu
soruyorsunuz?*

*Teşekkürler.*

MMustafaYILDIZ ***@***.***>, 25 Ağu 2023 Cum, 21:18 tarihinde
şunu yazdı:
